#!/bin/bash

t=`find ./ -maxdepth 2 -name "ajob*" |wc -l`
r=`find ./ -maxdepth 2 -name "run.ajob*" |wc -l`
w=`find ./ -maxdepth 2 -name "wait.ajob*" |wc -l`
d=`find ./ -maxdepth 2 -name "done.ajob*" |wc -l`

echo "waiting while finishing jobs on cluster"
while [[  $d -lt $t  ]]; do    
    echo $w $r $d $t
    rm -f ../status
    echo $w $r $d $t > ../status
    sleep 10
    t=`find ./ -maxdepth 2 -name "ajob*" |wc -l`
    r=`find ./ -maxdepth 2 -name "run.ajob*" |wc -l`
    w=`find ./ -maxdepth 2 -name "wait.ajob*" |wc -l`
    d=`find ./ -maxdepth 2 -name "done.ajob*" |wc -l`
done
echo $w $r $d $t

sleep 20