C/*--------------------------------------------------------
C// NC 1pi0 BG ratio table (after miss ID with polfit)
C// Enu(GeV),NCQE,NCRS,NCDI,NCCO+NCDF,NCTotal
C---------------------------------------------------------*/
      real*8 nm_ratioNC(10,6)
      data (nm_ratioNC(1,oi),oi=1,6) / 0.02500, 0, 0, 0, 0, 0 /
      data (nm_ratioNC(2,oi),oi=1,6) / 0.07500, 0, 0, 0, 0, 0 /
      data (nm_ratioNC(3,oi),oi=1,6) / 0.12500, 0, 0, 0, 0, 0 /
      data (nm_ratioNC(4,oi),oi=1,6) / 0.17500, 0, 0, 0, 0, 0 /
      data (nm_ratioNC(5,oi),oi=1,6) / 0.22500, 0, 0, 0, 0.00009, 0.00009 /
      data (nm_ratioNC(6,oi),oi=1,6) / 0.27500, 0, 0.00001, 0, 0.00033, 0.00034 /
      data (nm_ratioNC(7,oi),oi=1,6) / 0.32500, 0, 0.00011, 0, 0.00070, 0.00081 /
      data (nm_ratioNC(8,oi),oi=1,6) / 0.37500, 0, 0.00037, 0, 0.00102, 0.00139 /
      data (nm_ratioNC(9,oi),oi=1,6) / 0.42500, 0, 0.00097, 0, 0.00125, 0.00222 /
      data (nm_ratioNC(10,oi),oi=1,6) / 0.47500, 0, 0.00171, 0, 0.00164, 0.00335 /
